// FORGE-152: per-agent root file (CLAUDE.md / AGENTS.md / GEMINI.md) prefix-block
// reader/writer. Each agent's root file is product-owned; Forge owns exactly
// one marker-delimited block at the top. This module knows the block shape
// and the per-agent prose variant (Claude uses native `@import`, Codex and
// Gemini use a prose directive — see spec/decisions/2026-05-21-claudemd-
// methodology-split.md §5).
//
// AgentKind values match src/schemas/settings.ts AgentsSchema enum:
// 'claude' | 'codex' | 'gemini'. The naming convention follows the existing
// primary_host_cli / review_host_cli fields rather than the "claude_code"
// long form the original design ADR proposed (see commit 8da3b79 / A1
// mid-implementation fork).

// FORGE-160: `cursor` joins the AgentKind union. Unlike the other three hosts —
// whose managed artifact is a TOP-LEVEL root file (CLAUDE.md / AGENTS.md /
// GEMINI.md) carrying a marker block + an @import/prose pointer — cursor's
// artifact is a NESTED `.cursor/rules/forge-context.mdc`. Cursor `.mdc` rules
// require YAML frontmatter as the FIRST bytes (plain `.md` is ignored, and
// `@file` imports inside rules are confirmed unreliable — forum #135663), so
// cursor INLINES the rendered methodology context verbatim inside the marker
// block rather than pointing at .forge/CONTEXT.md. See
// spec/decisions/2026-06-12-cursor-host.md (USER CHOICE A: inline verbatim).
export type AgentKind = 'claude' | 'codex' | 'gemini' | 'cursor';

export interface PrefixBlockInput {
  readonly repoUrl: string;
}

// FORGE-160: per-host policy — does the upgrade refresh loop CREATE this host's
// managed file when it's enabled but absent on disk? claude/codex/gemini share
// a top-level root file that is PRODUCT-OWNED (forge only stamps a marker block
// onto a file the user maintains), so the loop skips when it's missing. cursor's
// `.mdc` artifact is FULLY forge-owned (gitignored, regenerated per machine like
// CONTEXT.md), so the loop materializes it when enabled. Anything not listed
// here defaults to skip-if-missing.
export const MATERIALIZE_WHEN_ENABLED: Readonly<Record<AgentKind, boolean>> = {
  claude: false,
  codex: false,
  gemini: false,
  cursor: true,
} as const;

// Marker text is byte-stable across versions — once shipped, do not edit.
// Phase B's strict edit-detection compares the block between markers against
// a SHA of the bundled version. Changing marker text would force every
// adopter to run `forge upgrade --force`.
const MARKER_OPEN = '<!-- >>> forge-managed (do not edit between markers) >>> -->';
const MARKER_CLOSE = '<!-- <<< forge-managed <<< -->';

export const ROOT_FILE_BY_AGENT: Readonly<Record<AgentKind, string>> = {
  claude: 'CLAUDE.md',
  codex: 'AGENTS.md',
  gemini: 'GEMINI.md',
  // FORGE-160: nested, forge-owned, gitignored. The upgrade refresh loop
  // mkdir's `.cursor/rules/` and routes cursor through the dedicated
  // frontmatter-first assembly below — NEVER the generic prepend path.
  cursor: '.cursor/rules/forge-context.mdc',
} as const;

// FORGE-160: the `.mdc` frontmatter that MUST be the first bytes of cursor's
// rule file (plain `.md` is ignored by Cursor). `alwaysApply: true` makes the
// rule unconditionally injected into every Cursor session — the inline-verbatim
// breadcrumb (USER CHOICE A) needs unconditional inclusion because `@file`
// imports are unreliable.
const CURSOR_FRONTMATTER = [
  '---',
  'alwaysApply: true',
  'description: Forge methodology — read before any work in this repo.',
  '---',
].join('\n');

// Claude Code variant: uses native @import. Mentions the first-run approval
// dialog (per A2.5 + A0 verification) — Claude Code asks permission the first
// time it sees an @-import, and silently disables imports if declined.
// Without this prose, users hit a confusing degraded state (CLAUDE.md present
// but methodology missing from context) and don't know how to recover.
function claudeBody(input: PrefixBlockInput): string {
  return `> This project uses [Forge](${input.repoUrl}). The methodology below is
> imported from a local file regenerated by \`forge upgrade\`. New collaborator?
> Install Forge with:
>
> \`\`\`
> npm install -g @firatcand/forge
> forge upgrade
> \`\`\`
>
> **First time opening this repo in Claude Code?** You'll see a one-time prompt
> asking permission to load \`.forge/CONTEXT.md\`. Accept it — without that
> approval, Claude Code silently skips the import and the methodology context
> won't be available.

@.forge/CONTEXT.md

> The import below pulls in THIS project's spec — the synthesized BRIEF/PRD/SPEC
> (the "what", vs. the methodology "how" above). It is committed and generated by
> \`/ingest-spec\` (a stub until you run it), so it travels with the repo.

@spec/CONTEXT.md`;
}

// Codex / Gemini variant: no @import syntax (these agents don't support it).
// Prose directive instructs the agent to read .forge/CONTEXT.md before any
// work. Same recovery instructions as the claude variant (npm install + run
// forge upgrade) so a new dev onto any agent has a single bootstrap.
function proseBody(input: PrefixBlockInput): string {
  return `> This project uses [Forge](${input.repoUrl}). Before any work, read \`.forge/CONTEXT.md\`
> for the methodology this project follows. If that file is missing, install Forge with:
>
> \`\`\`
> npm install -g @firatcand/forge
> forge upgrade
> \`\`\`
>
> Note: \`.forge/CONTEXT.md\` is gitignored and regenerated per-developer by \`forge upgrade\`.
>
> For THIS project's spec — the synthesized BRIEF/PRD/SPEC — also read
> \`spec/CONTEXT.md\` (committed; generated by \`/ingest-spec\`, a stub until then).`;
}

// FORGE-160: cursor marker-block body INLINES the rendered methodology context
// verbatim (USER CHOICE A). The caller passes the same `desiredContext` string
// `forge upgrade` already computes in memory (renderContext output) so the rule
// file and .forge/CONTEXT.md never drift. A short preamble above the inlined
// context explains the breadcrumb + recovery path, mirroring the other hosts.
function cursorBody(input: PrefixBlockInput, inlinedContext: string): string {
  return `> This project uses [Forge](${input.repoUrl}). The methodology below is INLINED
> here (regenerated by \`forge upgrade\`) because Cursor \`.mdc\` rules cannot
> reliably \`@file\`-import \`.forge/CONTEXT.md\`. New collaborator? Install Forge:
>
> \`\`\`
> npm install -g @firatcand/forge
> forge upgrade
> \`\`\`
>
> Note: \`.cursor/rules/forge-context.mdc\` is gitignored and regenerated per
> developer by \`forge upgrade\` — do not hand-edit between the markers.
>
> For THIS project's spec — the synthesized BRIEF/PRD/SPEC — also read
> \`spec/CONTEXT.md\` (committed; generated by \`/ingest-spec\`, a stub until then).

${inlinedContext}`;
}

export function buildPrefixBlock(agent: AgentKind, input: PrefixBlockInput): string {
  if (agent === 'cursor') {
    // Defense in depth: the cursor artifact MUST be assembled via
    // buildCursorRuleFile (frontmatter-first + inlined context). Routing it
    // through the generic block builder would drop the frontmatter and inline
    // nothing. Callers that reach here for cursor have a wiring bug.
    throw new Error(
      'buildPrefixBlock: cursor uses buildCursorRuleFile(...) — the generic ' +
        'block builder would omit the .mdc frontmatter and the inlined context.',
    );
  }
  const body = agent === 'claude' ? claudeBody(input) : proseBody(input);
  return `${MARKER_OPEN}\n${body}\n${MARKER_CLOSE}\n`;
}

/**
 * FORGE-160: build the cursor marker block (open/close + inlined-context body).
 * Exposed so the upgrade refresh loop can compute the desired block and feed it
 * to {@link writeCursorRuleBody} for the marker-region replacement.
 */
export function buildCursorBlock(input: PrefixBlockInput, inlinedContext: string): string {
  return `${MARKER_OPEN}\n${cursorBody(input, inlinedContext)}\n${MARKER_CLOSE}\n`;
}

/**
 * FORGE-160: assemble a COMPLETE cursor rule file from scratch (frontmatter
 * FIRST, then a blank line, then the forge marker block). Used when the file is
 * absent and the refresh loop materializes it. For an EXISTING file with user
 * content below the markers, use {@link writeCursorRuleBody} instead.
 */
export function buildCursorRuleFile(input: PrefixBlockInput, inlinedContext: string): string {
  return `${CURSOR_FRONTMATTER}\n\n${buildCursorBlock(input, inlinedContext)}`;
}

/**
 * FORGE-160: frontmatter-first wrapper around {@link replacePrefixBlock}. The
 * generic helper would prepend the marker block ABOVE the `.mdc` frontmatter,
 * which Cursor requires to be the first bytes — so cursor NEVER calls
 * replacePrefixBlock directly. This splits the existing file into
 * (frontmatter, post-frontmatter body), runs the marker replacement on the body
 * alone, and reattaches the frontmatter on top. If the existing file has no
 * recognizable frontmatter (hand-stripped, or a brand-new empty buffer), the
 * canonical frontmatter is re-attached so the file is always Cursor-valid.
 */
export function writeCursorRuleBody(
  existingContents: string,
  desiredBlock: string,
): string {
  const split = splitCursorFrontmatter(existingContents);
  const newBody = replacePrefixBlock(split.body, desiredBlock);
  return `${split.frontmatter}\n\n${newBody}`;
}

interface CursorSplit {
  /** The leading `---\n...\n---` frontmatter (canonical if none was present). */
  readonly frontmatter: string;
  /** Everything after the frontmatter (and the blank line that followed it). */
  readonly body: string;
}

// Match a leading YAML frontmatter block: `---` on the first line, any content,
// a closing `---` line, and an optional trailing newline run. Anchored at start.
const FRONTMATTER_RE = /^---\n[\s\S]*?\n---\n?/;

function splitCursorFrontmatter(contents: string): CursorSplit {
  const m = contents.match(FRONTMATTER_RE);
  if (!m) {
    // No frontmatter on disk (empty file, or a user stripped it). Re-attach the
    // canonical frontmatter and treat the whole buffer as body.
    return { frontmatter: CURSOR_FRONTMATTER, body: contents };
  }
  // Preserve the user's frontmatter byte-for-byte (minus its trailing newlines,
  // which we normalize to a single blank-line separator on reattach).
  const fm = m[0].replace(/\n+$/, '');
  const body = contents.slice(m[0].length).replace(/^\n+/, '');
  return { frontmatter: fm, body };
}

/**
 * FORGE-160: extract the marker-block BODY of a cursor rule file with the
 * frontmatter AND the markers stripped — i.e. the preamble + inlined context.
 * Used by render-worker-prompt to source cursor conventions. Returns '' when no
 * marker block is present.
 */
export function cursorConventionsBody(contents: string): string {
  const split = splitCursorFrontmatter(contents);
  const block = extractPrefixBlock(split.body);
  if (block === null) return '';
  // Strip the markers (and their surrounding newlines) from the block.
  return block
    .replace(escapeForLineRemoval(MARKER_OPEN), '')
    .replace(escapeForLineRemoval(MARKER_CLOSE), '')
    .replace(/^\n+/, '')
    .replace(/\n+$/, '');
}

function escapeForLineRemoval(marker: string): RegExp {
  return new RegExp(`${escapeRegex(marker)}\\n?`);
}

// Regex matches the open marker, any content (including newlines), and the
// close marker, optionally followed by one trailing newline. The non-greedy
// `[\s\S]*?` ensures we only match a single block, not across multiple
// hypothetical blocks if a user accidentally pastes a second pair.
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const blockRegex = new RegExp(
  `${escapeRegex(MARKER_OPEN)}[\\s\\S]*?${escapeRegex(MARKER_CLOSE)}\\n?`,
  'm',
);

// Replace the marker block in `fileContents` with `newBlock`. If no existing
// block is present, prepend `newBlock` followed by a blank line separator.
// User content outside the markers is preserved exactly — this is the
// load-bearing invariant Phase B's `forge upgrade --force` relies on.
export function replacePrefixBlock(fileContents: string, newBlock: string): string {
  if (blockRegex.test(fileContents)) {
    return fileContents.replace(blockRegex, newBlock);
  }
  if (fileContents.length === 0) return newBlock;
  return `${newBlock}\n${fileContents}`;
}

export function extractPrefixBlock(fileContents: string): string | null {
  const match = fileContents.match(blockRegex);
  return match ? match[0] : null;
}

// Returns the file's body with the forge-managed block (and any leading
// blank lines it leaves behind) stripped. Useful for Phase C migration:
// extract the user's product content from a v0.4-format CLAUDE.md.
export function bodyWithoutPrefixBlock(fileContents: string): string {
  return fileContents.replace(blockRegex, '').replace(/^\n+/, '');
}

/**
 * FORGE-160 (GPT-5.5 review): cursor-aware user-body extraction for accounting
 * (e.g. `forge status`). A cursor `.mdc` is `frontmatter + marker block`, both
 * forge-owned — only content BELOW the marker block is the user's. The generic
 * {@link bodyWithoutPrefixBlock} strips only the marker block, so the forge
 * frontmatter leaks into the "user body" byte count and a pristine artifact
 * looks user-edited. This strips the frontmatter FIRST (via the same split the
 * write path uses), then the marker block — so a pristine cursor `.mdc` reports
 * an EMPTY user body.
 */
export function cursorUserBody(fileContents: string): string {
  const split = splitCursorFrontmatter(fileContents);
  return bodyWithoutPrefixBlock(split.body);
}
