// FORGE-152: per-agent root file (CLAUDE.md / AGENTS.md / GEMINI.md) prefix-block
// reader/writer. Each agent's root file is product-owned; Forge owns exactly
// one marker-delimited block at the top. This module knows the block shape
// and the per-agent prose variant (Claude uses native `@import`, Codex and
// Gemini use a prose directive — see spec/decisions/2026-05-21-claudemd-
// methodology-split.md §5).
//
// AgentKind values match src/schemas/settings.ts AgentsSchema enum:
// 'claude' | 'codex' | 'gemini'. The naming convention follows the existing
// primary_host_cli / review_host_cli fields rather than the "claude_code"
// long form the original design ADR proposed (see commit 8da3b79 / A1
// mid-implementation fork).

export type AgentKind = 'claude' | 'codex' | 'gemini';

export interface PrefixBlockInput {
  readonly repoUrl: string;
}

// Marker text is byte-stable across versions — once shipped, do not edit.
// Phase B's strict edit-detection compares the block between markers against
// a SHA of the bundled version. Changing marker text would force every
// adopter to run `forge upgrade --force`.
const MARKER_OPEN = '<!-- >>> forge-managed (do not edit between markers) >>> -->';
const MARKER_CLOSE = '<!-- <<< forge-managed <<< -->';

export const ROOT_FILE_BY_AGENT: Readonly<Record<AgentKind, string>> = {
  claude: 'CLAUDE.md',
  codex: 'AGENTS.md',
  gemini: 'GEMINI.md',
} as const;

// Claude Code variant: uses native @import. Mentions the first-run approval
// dialog (per A2.5 + A0 verification) — Claude Code asks permission the first
// time it sees an @-import, and silently disables imports if declined.
// Without this prose, users hit a confusing degraded state (CLAUDE.md present
// but methodology missing from context) and don't know how to recover.
function claudeBody(input: PrefixBlockInput): string {
  return `> This project uses [Forge](${input.repoUrl}). The methodology below is
> imported from a local file regenerated by \`forge upgrade\`. New collaborator?
> Install Forge with:
>
> \`\`\`
> npm install -g @firatcand/forge
> forge upgrade
> \`\`\`
>
> **First time opening this repo in Claude Code?** You'll see a one-time prompt
> asking permission to load \`.forge/CONTEXT.md\`. Accept it — without that
> approval, Claude Code silently skips the import and the methodology context
> won't be available.

@.forge/CONTEXT.md`;
}

// Codex / Gemini variant: no @import syntax (these agents don't support it).
// Prose directive instructs the agent to read .forge/CONTEXT.md before any
// work. Same recovery instructions as the claude variant (npm install + run
// forge upgrade) so a new dev onto any agent has a single bootstrap.
function proseBody(input: PrefixBlockInput): string {
  return `> This project uses [Forge](${input.repoUrl}). Before any work, read \`.forge/CONTEXT.md\`
> for the methodology this project follows. If that file is missing, install Forge with:
>
> \`\`\`
> npm install -g @firatcand/forge
> forge upgrade
> \`\`\`
>
> Note: \`.forge/CONTEXT.md\` is gitignored and regenerated per-developer by \`forge upgrade\`.`;
}

export function buildPrefixBlock(agent: AgentKind, input: PrefixBlockInput): string {
  const body = agent === 'claude' ? claudeBody(input) : proseBody(input);
  return `${MARKER_OPEN}\n${body}\n${MARKER_CLOSE}\n`;
}

// Regex matches the open marker, any content (including newlines), and the
// close marker, optionally followed by one trailing newline. The non-greedy
// `[\s\S]*?` ensures we only match a single block, not across multiple
// hypothetical blocks if a user accidentally pastes a second pair.
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const blockRegex = new RegExp(
  `${escapeRegex(MARKER_OPEN)}[\\s\\S]*?${escapeRegex(MARKER_CLOSE)}\\n?`,
  'm',
);

// Replace the marker block in `fileContents` with `newBlock`. If no existing
// block is present, prepend `newBlock` followed by a blank line separator.
// User content outside the markers is preserved exactly — this is the
// load-bearing invariant Phase B's `forge upgrade --force` relies on.
export function replacePrefixBlock(fileContents: string, newBlock: string): string {
  if (blockRegex.test(fileContents)) {
    return fileContents.replace(blockRegex, newBlock);
  }
  if (fileContents.length === 0) return newBlock;
  return `${newBlock}\n${fileContents}`;
}

export function extractPrefixBlock(fileContents: string): string | null {
  const match = fileContents.match(blockRegex);
  return match ? match[0] : null;
}

// Returns the file's body with the forge-managed block (and any leading
// blank lines it leaves behind) stripped. Useful for Phase C migration:
// extract the user's product content from a v0.4-format CLAUDE.md.
export function bodyWithoutPrefixBlock(fileContents: string): string {
  return fileContents.replace(blockRegex, '').replace(/^\n+/, '');
}
