import { join } from 'node:path';
import { QuestionChannelError } from './errors.ts';
import { TASK_ID_RE, TASK_ID_MAX_LEN } from '../../schemas/task-id.ts';

// task_id, attempt_id, and question_id are interpolated into filesystem paths.
// Untrusted segments could escape the orchestrator subtree (`../../etc/passwd`)
// or trip cross-platform path semantics (NUL bytes, leading dots on POSIX,
// reserved names on Windows). Validation delegates to the unified task-id
// primitive (FORGE-130, src/schemas/task-id.ts), which is the same shape used by
// UUIDv7 run/attempt/question segments (lower-hex + hyphens, leading alnum) and
// the Linear/GitHub/phases issue-id shapes. This WRAPS the primitive: it keeps
// the QuestionChannelError INVALID_ID code and the (length / empty / charset)
// message granularity callers already depend on. Note this narrows the prior
// `/^[A-Za-z0-9_-]+$/` by rejecting a leading `_`/`-` and adding `.` — no
// run/attempt/question id (all UUID-shaped, leading hex) relied on that.
const ID_SEGMENT_MAX_LEN = TASK_ID_MAX_LEN;

export function validateIdSegment(value: string, fieldName: string): string {
  if (typeof value !== 'string' || value.length === 0) {
    throw new QuestionChannelError(
      'INVALID_ID',
      `${fieldName} must be a non-empty string`,
      { fieldName, value },
    );
  }
  if (value.length > ID_SEGMENT_MAX_LEN) {
    throw new QuestionChannelError(
      'INVALID_ID',
      `${fieldName} exceeds ${ID_SEGMENT_MAX_LEN} characters`,
      { fieldName, length: value.length },
    );
  }
  if (!TASK_ID_RE.test(value)) {
    throw new QuestionChannelError(
      'INVALID_ID',
      `${fieldName} must match /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/ (alphanumeric start; letters, digits, . _ -)`,
      { fieldName, value },
    );
  }
  return value;
}

// Path computation for the v2 task-keyed layout.
// See spec/ORCHESTRATOR.md §Filesystem layout. Every helper here is pure: it
// validates ids and joins paths, no I/O.

export function tasksRootDir(forgeDir: string): string {
  return join(forgeDir, 'orchestrator', 'tasks');
}

export function taskDir(forgeDir: string, taskId: string): string {
  return join(tasksRootDir(forgeDir), validateIdSegment(taskId, 'taskId'));
}

export function attemptsDir(forgeDir: string, taskId: string): string {
  return join(taskDir(forgeDir, taskId), 'attempts');
}

export function attemptDir(
  forgeDir: string,
  taskId: string,
  attemptId: string,
): string {
  return join(
    attemptsDir(forgeDir, taskId),
    validateIdSegment(attemptId, 'attemptId'),
  );
}

export function questionsDir(
  forgeDir: string,
  taskId: string,
  attemptId: string,
): string {
  return join(attemptDir(forgeDir, taskId, attemptId), 'questions');
}

export function answersDir(
  forgeDir: string,
  taskId: string,
  attemptId: string,
): string {
  return join(attemptDir(forgeDir, taskId, attemptId), 'answers');
}

export function questionFilePath(
  forgeDir: string,
  taskId: string,
  attemptId: string,
  questionId: string,
): string {
  return join(
    questionsDir(forgeDir, taskId, attemptId),
    `${validateIdSegment(questionId, 'questionId')}.json`,
  );
}

export function answerFilePath(
  forgeDir: string,
  taskId: string,
  attemptId: string,
  questionId: string,
): string {
  return join(
    answersDir(forgeDir, taskId, attemptId),
    `${validateIdSegment(questionId, 'questionId')}.json`,
  );
}

// State, lease, claim-history, manifest, and events path helpers.
// These new paths live in the same module to keep all path logic co-located.
// Path computation is pure (no I/O). Validation is done by validateIdSegment.

export function stateFilePath(forgeDir: string, taskId: string): string {
  return join(taskDir(forgeDir, taskId), 'state.json');
}

export function leaseFilePath(forgeDir: string, taskId: string): string {
  return join(taskDir(forgeDir, taskId), 'lease.json');
}

export function claimHistoryFilePath(forgeDir: string, taskId: string): string {
  return join(taskDir(forgeDir, taskId), 'claim-history.jsonl');
}

export function manifestFilePath(
  forgeDir: string,
  taskId: string,
  attemptId: string,
): string {
  return join(attemptDir(forgeDir, taskId, attemptId), 'manifest.json');
}

export function eventsFilePath(
  forgeDir: string,
  taskId: string,
  attemptId: string,
): string {
  return join(attemptDir(forgeDir, taskId, attemptId), 'events.jsonl');
}

// Legacy paths — referenced by gc to detect and migrate v1 trees.

export function legacyQuestionsDir(forgeDir: string): string {
  return join(forgeDir, 'questions');
}

export function legacyAnswersDir(forgeDir: string): string {
  return join(forgeDir, 'answers');
}

export function legacyArchiveRoot(forgeDir: string): string {
  return join(forgeDir, 'orchestrator', 'legacy');
}

export function legacyArchiveSession(
  forgeDir: string,
  isoTimestamp: string,
): string {
  // Timestamp is generated by the gc verb itself, not by user input — but
  // colons in ISO strings are fine on POSIX and we sanitize for Windows-style
  // safety with a permissive replace anyway.
  const safe = isoTimestamp.replace(/[^0-9A-Za-z]/g, '-');
  return join(legacyArchiveRoot(forgeDir), safe);
}
